-- =============================================================================
-- Sistema Fintech (SF) — 01-create-tables.sql
-- -----------------------------------------------------------------------------
-- Cria o modelo físico v2 (Fase 4): 10 tabelas, constraints nomeadas, índices
-- e comentários. Fonte da verdade: docs/05-banco-de-dados/dicionario-de-dados.md
--
-- Decisões aplicadas (docs/05-banco-de-dados/decisoes-tecnicas.md):
--   D-01 T_SF_INVESTIMENTO      D-02 PK por IDENTITY      D-04 domínios por CHECK
--   D-13 e-mail único           D-14 FK composta conta/usuário
--   D-15 dt_pagamento opcional  D-16 sintaxe Oracle 19c   D-17 taxas em fração
--
-- Autora : Larissa Gomes de Carvalho — RM 571266 — 1TDSOA
-- Versão : 2.0 (Fase 4)
-- Ordem  : 00-drop-tables.sql -> 01-create-tables.sql -> 02-seed.sql
-- =============================================================================
SET DEFINE OFF

-- -----------------------------------------------------------------------------
-- Nível 1: tabelas sem dependências
-- -----------------------------------------------------------------------------

CREATE TABLE T_SF_USUARIO (
    id_usuario   NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome         VARCHAR2(150)  NOT NULL,
    email        VARCHAR2(255)  NOT NULL,
    senha        VARCHAR2(255)  NOT NULL,
    avatar       VARCHAR2(500),
    dt_cadastro  DATE           DEFAULT SYSDATE NOT NULL,
    ativo        CHAR(1)        DEFAULT 'S'     NOT NULL,
    CONSTRAINT PK_T_SF_USUARIO     PRIMARY KEY (id_usuario),
    CONSTRAINT UK_SF_USUARIO_EMAIL UNIQUE (email),
    CONSTRAINT CK_SF_USUARIO_EMAIL CHECK (email LIKE '_%@_%._%'),
    CONSTRAINT CK_SF_USUARIO_ATIVO CHECK (ativo IN ('S', 'N'))
);

CREATE TABLE T_SF_CATEGORIA (
    id_categoria NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome         VARCHAR2(80)   NOT NULL,
    tipo         VARCHAR2(10)   NOT NULL,
    CONSTRAINT PK_T_SF_CATEGORIA    PRIMARY KEY (id_categoria),
    CONSTRAINT UK_SF_CATEGORIA_NOME UNIQUE (nome, tipo),
    CONSTRAINT CK_SF_CATEGORIA_TIPO CHECK (tipo IN ('RECEITA', 'GASTO'))
);

-- -----------------------------------------------------------------------------
-- Nível 2: dependem de T_SF_USUARIO
-- -----------------------------------------------------------------------------

CREATE TABLE T_SF_CONTA_BANCARIA (
    id_conta     NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario   NUMBER(10)     NOT NULL,
    nm_banco     VARCHAR2(100)  NOT NULL,
    tipo_conta   VARCHAR2(20)   NOT NULL,
    nr_conta     VARCHAR2(20)   NOT NULL,
    ativa        CHAR(1)        DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_T_SF_CONTA_BANCARIA PRIMARY KEY (id_conta),
    CONSTRAINT FK_SF_CONTA_USUARIO    FOREIGN KEY (id_usuario)
        REFERENCES T_SF_USUARIO (id_usuario),
    -- Alvo das FKs compostas de receita/gasto/investimento (D-14)
    CONSTRAINT UK_SF_CONTA_USUARIO    UNIQUE (id_conta, id_usuario),
    CONSTRAINT UK_SF_CONTA_NUMERO     UNIQUE (id_usuario, nm_banco, nr_conta),
    CONSTRAINT CK_SF_CONTA_TIPO_CONTA CHECK (tipo_conta IN
        ('CORRENTE', 'POUPANCA', 'PAGAMENTO', 'SALARIO', 'INVESTIMENTO')),
    CONSTRAINT CK_SF_CONTA_ATIVA      CHECK (ativa IN ('S', 'N'))
);

CREATE TABLE T_SF_DIVIDA (
    id_divida       NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario      NUMBER(10)     NOT NULL,
    descricao       VARCHAR2(200)  NOT NULL,
    tipo            VARCHAR2(20)   NOT NULL,
    vl_total        NUMBER(15,2)   NOT NULL,
    saldo_devedor   NUMBER(15,2)   NOT NULL,
    total_parcelas  NUMBER(4)      NOT NULL,
    tx_juros_mensal NUMBER(5,4),
    status          VARCHAR2(15)   NOT NULL,
    dt_inicio       DATE           NOT NULL,
    CONSTRAINT PK_T_SF_DIVIDA              PRIMARY KEY (id_divida),
    CONSTRAINT FK_SF_DIVIDA_USUARIO        FOREIGN KEY (id_usuario)
        REFERENCES T_SF_USUARIO (id_usuario),
    CONSTRAINT CK_SF_DIVIDA_TIPO           CHECK (tipo IN
        ('CARTAO', 'EMPRESTIMO', 'FINANCIAMENTO', 'CHEQUE_ESPECIAL', 'OUTROS')),
    CONSTRAINT CK_SF_DIVIDA_VL_TOTAL       CHECK (vl_total > 0),
    CONSTRAINT CK_SF_DIVIDA_SALDO_DEVEDOR  CHECK (saldo_devedor >= 0),
    CONSTRAINT CK_SF_DIVIDA_TOTAL_PARCELAS CHECK (total_parcelas > 0),
    CONSTRAINT CK_SF_DIVIDA_TX_JUROS       CHECK (tx_juros_mensal >= 0),
    CONSTRAINT CK_SF_DIVIDA_STATUS         CHECK (status IN ('EM_DIA', 'ATRASADA', 'QUITADA'))
);

CREATE TABLE T_SF_META (
    id_meta       NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario    NUMBER(10)     NOT NULL,
    nome          VARCHAR2(150)  NOT NULL,
    vl_alvo       NUMBER(15,2)   NOT NULL,
    vl_acumulado  NUMBER(15,2)   DEFAULT 0       NOT NULL,
    prazo         DATE           NOT NULL,
    status        VARCHAR2(15)   DEFAULT 'ATIVA' NOT NULL,
    dt_criacao    DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_T_SF_META            PRIMARY KEY (id_meta),
    CONSTRAINT FK_SF_META_USUARIO      FOREIGN KEY (id_usuario)
        REFERENCES T_SF_USUARIO (id_usuario),
    CONSTRAINT CK_SF_META_VL_ALVO      CHECK (vl_alvo > 0),
    CONSTRAINT CK_SF_META_VL_ACUMULADO CHECK (vl_acumulado >= 0),
    CONSTRAINT CK_SF_META_STATUS       CHECK (status IN ('ATIVA', 'CONCLUIDA', 'CANCELADA'))
);

-- -----------------------------------------------------------------------------
-- Nível 3: lançamentos e filhos de dívida/meta
-- -----------------------------------------------------------------------------

CREATE TABLE T_SF_RECEITA (
    id_receita      NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario      NUMBER(10)     NOT NULL,
    id_conta        NUMBER(10)     NOT NULL,
    id_categoria    NUMBER(10)     NOT NULL,
    descricao       VARCHAR2(300)  NOT NULL,
    valor           NUMBER(15,2)   NOT NULL,
    dt_recebimento  DATE           NOT NULL,
    origem          VARCHAR2(20),
    recorrencia     VARCHAR2(10),
    comprovante     VARCHAR2(500),
    CONSTRAINT PK_T_SF_RECEITA           PRIMARY KEY (id_receita),
    CONSTRAINT FK_SF_RECEITA_USUARIO     FOREIGN KEY (id_usuario)
        REFERENCES T_SF_USUARIO (id_usuario),
    CONSTRAINT FK_SF_RECEITA_CONTA       FOREIGN KEY (id_conta, id_usuario)
        REFERENCES T_SF_CONTA_BANCARIA (id_conta, id_usuario),
    CONSTRAINT FK_SF_RECEITA_CATEGORIA   FOREIGN KEY (id_categoria)
        REFERENCES T_SF_CATEGORIA (id_categoria),
    CONSTRAINT CK_SF_RECEITA_VALOR       CHECK (valor > 0),
    CONSTRAINT CK_SF_RECEITA_ORIGEM      CHECK (origem IN
        ('SALARIO', 'FREELANCE', 'INVESTIMENTO', 'OUTROS')),
    CONSTRAINT CK_SF_RECEITA_RECORRENCIA CHECK (recorrencia IN ('UNICA', 'MENSAL', 'ANUAL'))
);

CREATE TABLE T_SF_GASTO (
    id_gasto      NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario    NUMBER(10)     NOT NULL,
    id_conta      NUMBER(10)     NOT NULL,
    id_categoria  NUMBER(10)     NOT NULL,
    descricao     VARCHAR2(300)  NOT NULL,
    valor         NUMBER(15,2)   NOT NULL,
    dt_gasto      DATE           NOT NULL,
    tipo          VARCHAR2(10),
    comprovante   VARCHAR2(500),
    CONSTRAINT PK_T_SF_GASTO         PRIMARY KEY (id_gasto),
    CONSTRAINT FK_SF_GASTO_USUARIO   FOREIGN KEY (id_usuario)
        REFERENCES T_SF_USUARIO (id_usuario),
    CONSTRAINT FK_SF_GASTO_CONTA     FOREIGN KEY (id_conta, id_usuario)
        REFERENCES T_SF_CONTA_BANCARIA (id_conta, id_usuario),
    CONSTRAINT FK_SF_GASTO_CATEGORIA FOREIGN KEY (id_categoria)
        REFERENCES T_SF_CATEGORIA (id_categoria),
    CONSTRAINT CK_SF_GASTO_VALOR     CHECK (valor > 0),
    CONSTRAINT CK_SF_GASTO_TIPO      CHECK (tipo IN ('FIXO', 'VARIAVEL'))
);

CREATE TABLE T_SF_INVESTIMENTO (
    id_investimento   NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario        NUMBER(10)     NOT NULL,
    id_conta          NUMBER(10)     NOT NULL,
    nm_investimento   VARCHAR2(150)  NOT NULL,
    tipo              VARCHAR2(30)   NOT NULL,
    instituicao       VARCHAR2(100),
    vl_aplicado       NUMBER(15,2)   NOT NULL,
    tx_rentabilidade  NUMBER(7,4),
    dt_aplicacao      DATE           NOT NULL,
    dt_vencimento     DATE,
    status            VARCHAR2(15)   DEFAULT 'ATIVO' NOT NULL,
    CONSTRAINT PK_T_SF_INVESTIMENTO       PRIMARY KEY (id_investimento),
    CONSTRAINT FK_SF_INVEST_USUARIO       FOREIGN KEY (id_usuario)
        REFERENCES T_SF_USUARIO (id_usuario),
    CONSTRAINT FK_SF_INVEST_CONTA         FOREIGN KEY (id_conta, id_usuario)
        REFERENCES T_SF_CONTA_BANCARIA (id_conta, id_usuario),
    CONSTRAINT CK_SF_INVEST_TIPO          CHECK (tipo IN
        ('CDB', 'LCI', 'LCA', 'TESOURO', 'ACOES', 'FII', 'FUNDO', 'POUPANCA', 'CRIPTO', 'OUTROS')),
    CONSTRAINT CK_SF_INVEST_VL_APLICADO   CHECK (vl_aplicado > 0),
    CONSTRAINT CK_SF_INVEST_TX_RENTAB     CHECK (tx_rentabilidade >= 0),
    CONSTRAINT CK_SF_INVEST_DT_VENCIMENTO CHECK (dt_vencimento >= dt_aplicacao),
    CONSTRAINT CK_SF_INVEST_STATUS        CHECK (status IN ('ATIVO', 'RESGATADO', 'VENCIDO'))
);

CREATE TABLE T_SF_PARCELA (
    id_parcela     NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_divida      NUMBER(10)    NOT NULL,
    nr_parcela     NUMBER(4)     NOT NULL,
    vl_parcela     NUMBER(15,2)  NOT NULL,
    dt_vencimento  DATE          NOT NULL,
    dt_pagamento   DATE,
    status         VARCHAR2(15)  NOT NULL,
    CONSTRAINT PK_T_SF_PARCELA          PRIMARY KEY (id_parcela),
    CONSTRAINT FK_SF_PARCELA_DIVIDA     FOREIGN KEY (id_divida)
        REFERENCES T_SF_DIVIDA (id_divida),
    CONSTRAINT UK_SF_PARCELA_NUMERO     UNIQUE (id_divida, nr_parcela),
    CONSTRAINT CK_SF_PARCELA_NR_PARCELA CHECK (nr_parcela > 0),
    CONSTRAINT CK_SF_PARCELA_VL_PARCELA CHECK (vl_parcela > 0),
    CONSTRAINT CK_SF_PARCELA_STATUS     CHECK (status IN ('PENDENTE', 'PAGA', 'ATRASADA')),
    -- Parcela paga precisa ter data de pagamento (D-15)
    CONSTRAINT CK_SF_PARCELA_PAGAMENTO  CHECK (status <> 'PAGA' OR dt_pagamento IS NOT NULL)
);

CREATE TABLE T_SF_APORTE_META (
    id_aporte   NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_meta     NUMBER(10)     NOT NULL,
    valor       NUMBER(15,2)   NOT NULL,
    dt_aporte   DATE           NOT NULL,
    observacao  VARCHAR2(300),
    CONSTRAINT PK_T_SF_APORTE_META PRIMARY KEY (id_aporte),
    CONSTRAINT FK_SF_APORTE_META   FOREIGN KEY (id_meta)
        REFERENCES T_SF_META (id_meta),
    CONSTRAINT CK_SF_APORTE_VALOR  CHECK (valor > 0)
);

-- -----------------------------------------------------------------------------
-- Índices (Oracle não indexa FKs automaticamente)
-- -----------------------------------------------------------------------------
CREATE INDEX IX_SF_RECEITA_USUARIO_DATA ON T_SF_RECEITA (id_usuario, dt_recebimento);
CREATE INDEX IX_SF_RECEITA_CONTA        ON T_SF_RECEITA (id_conta, id_usuario);
CREATE INDEX IX_SF_RECEITA_CATEGORIA    ON T_SF_RECEITA (id_categoria);

CREATE INDEX IX_SF_GASTO_USUARIO_DATA   ON T_SF_GASTO (id_usuario, dt_gasto);
CREATE INDEX IX_SF_GASTO_CONTA          ON T_SF_GASTO (id_conta, id_usuario);
CREATE INDEX IX_SF_GASTO_CATEGORIA      ON T_SF_GASTO (id_categoria);

CREATE INDEX IX_SF_INVEST_USUARIO_DATA  ON T_SF_INVESTIMENTO (id_usuario, dt_aplicacao);
CREATE INDEX IX_SF_INVEST_CONTA         ON T_SF_INVESTIMENTO (id_conta, id_usuario);

CREATE INDEX IX_SF_DIVIDA_USUARIO       ON T_SF_DIVIDA (id_usuario);
CREATE INDEX IX_SF_META_USUARIO         ON T_SF_META (id_usuario);
CREATE INDEX IX_SF_APORTE_META          ON T_SF_APORTE_META (id_meta);

-- -----------------------------------------------------------------------------
-- Comentários (documentação no próprio catálogo do banco)
-- -----------------------------------------------------------------------------
COMMENT ON TABLE  T_SF_USUARIO                     IS 'Usuários do sistema Fintech';
COMMENT ON COLUMN T_SF_USUARIO.senha               IS 'Hash da senha gerado pela aplicação; nunca retornado em consultas';
COMMENT ON COLUMN T_SF_USUARIO.ativo               IS 'S = ativo, N = inativo';

COMMENT ON TABLE  T_SF_CONTA_BANCARIA              IS 'Contas bancárias dos usuários';
COMMENT ON COLUMN T_SF_CONTA_BANCARIA.tipo_conta   IS 'CORRENTE, POUPANCA, PAGAMENTO, SALARIO, INVESTIMENTO';

COMMENT ON TABLE  T_SF_CATEGORIA                   IS 'Categorias de receitas e gastos';
COMMENT ON COLUMN T_SF_CATEGORIA.tipo              IS 'RECEITA ou GASTO';

COMMENT ON TABLE  T_SF_RECEITA                     IS 'Entradas de dinheiro';
COMMENT ON COLUMN T_SF_RECEITA.origem              IS 'SALARIO, FREELANCE, INVESTIMENTO, OUTROS';
COMMENT ON COLUMN T_SF_RECEITA.recorrencia         IS 'UNICA, MENSAL, ANUAL';

COMMENT ON TABLE  T_SF_GASTO                       IS 'Saídas de dinheiro (despesas)';
COMMENT ON COLUMN T_SF_GASTO.tipo                  IS 'FIXO ou VARIAVEL';

COMMENT ON TABLE  T_SF_INVESTIMENTO                IS 'Aplicações financeiras dos usuários (novo na Fase 4)';
COMMENT ON COLUMN T_SF_INVESTIMENTO.tipo           IS 'CDB, LCI, LCA, TESOURO, ACOES, FII, FUNDO, POUPANCA, CRIPTO, OUTROS';
COMMENT ON COLUMN T_SF_INVESTIMENTO.tx_rentabilidade IS 'Rentabilidade anual em fração decimal (0.1250 = 12,5% a.a.)';
COMMENT ON COLUMN T_SF_INVESTIMENTO.status         IS 'ATIVO, RESGATADO, VENCIDO';

COMMENT ON TABLE  T_SF_DIVIDA                      IS 'Dívidas dos usuários';
COMMENT ON COLUMN T_SF_DIVIDA.tx_juros_mensal      IS 'Juros ao mês em fração decimal (0.0299 = 2,99% a.m.)';
COMMENT ON COLUMN T_SF_DIVIDA.status               IS 'EM_DIA, ATRASADA, QUITADA';

COMMENT ON TABLE  T_SF_PARCELA                     IS 'Parcelas das dívidas';
COMMENT ON COLUMN T_SF_PARCELA.dt_pagamento        IS 'Nula enquanto a parcela não for paga';
COMMENT ON COLUMN T_SF_PARCELA.status              IS 'PENDENTE, PAGA, ATRASADA';

COMMENT ON TABLE  T_SF_META                        IS 'Metas financeiras (sonhos) dos usuários';
COMMENT ON COLUMN T_SF_META.status                 IS 'ATIVA, CONCLUIDA, CANCELADA';

COMMENT ON TABLE  T_SF_APORTE_META                 IS 'Valores guardados para cada meta';
